//! Request identifiers and pending JSON-RPC response tracking.

use std::collections::HashMap;
use std::fmt;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Mutex;

use serde_json::Value;
use tokio::sync::oneshot;

use crate::{Error, Result};

/// An identifier generated by this client for one JSON-RPC request.
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq, PartialOrd, Ord)]
pub struct RequestId(u64);

impl RequestId {
    pub(crate) const fn new(value: u64) -> Self {
        Self(value)
    }

    /// Returns the numeric JSON-RPC request identifier.
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl fmt::Display for RequestId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

/// Concurrent registry for calls that are awaiting a response.
pub(crate) struct PendingRequests {
    next_id: AtomicU64,
    waiters: Mutex<HashMap<RequestId, oneshot::Sender<Result<Value>>>>,
}

impl PendingRequests {
    pub(crate) fn new() -> Self {
        Self {
            next_id: AtomicU64::new(1),
            waiters: Mutex::new(HashMap::new()),
        }
    }

    pub(crate) fn register(&self) -> (RequestId, oneshot::Receiver<Result<Value>>) {
        let id = self.next_id();
        let (sender, receiver) = oneshot::channel();
        self.waiters
            .lock()
            .expect("pending request lock poisoned")
            .insert(id, sender);
        (id, receiver)
    }

    pub(crate) fn resolve(&self, id: RequestId, result: Result<Value>) -> bool {
        self.waiters
            .lock()
            .expect("pending request lock poisoned")
            .remove(&id)
            .is_some_and(|sender| sender.send(result).is_ok())
    }

    pub(crate) fn remove(&self, id: RequestId) {
        let _ = self
            .waiters
            .lock()
            .expect("pending request lock poisoned")
            .remove(&id);
    }

    pub(crate) fn fail_all(&self, error: Error) {
        let pending =
            std::mem::take(&mut *self.waiters.lock().expect("pending request lock poisoned"));
        for (_, sender) in pending {
            let _ = sender.send(Err(error.clone()));
        }
    }

    fn next_id(&self) -> RequestId {
        loop {
            let id = self.next_id.fetch_add(1, Ordering::Relaxed);
            if id != 0 {
                return RequestId::new(id);
            }
        }
    }
}
