use std::collections::HashMap;
use std::fmt;
use std::str::FromStr;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex, RwLock};
use std::time::Duration;

use futures_util::{SinkExt, StreamExt};
use serde_json::Value;
use tokio::sync::{broadcast, mpsc, oneshot, watch};
use tokio::task::JoinHandle;
use tokio::time::timeout;
use tokio_tungstenite::connect_async;
use tokio_tungstenite::tungstenite::client::IntoClientRequest;
use tokio_tungstenite::tungstenite::http::header::{AUTHORIZATION, ORIGIN, SEC_WEBSOCKET_PROTOCOL};
use tokio_tungstenite::tungstenite::http::HeaderValue;
use tokio_tungstenite::tungstenite::{Error as WebSocketError, Message};
use url::Url;

use crate::transport::{parse_inbound, serialize_request, Inbound, OutboundRequest};
use crate::{Auth, Error, RawApi, Result};

const DEFAULT_REQUEST_TIMEOUT: Duration = Duration::from_secs(10);
const DEFAULT_CHANNEL_CAPACITY: usize = 128;
const NOTIFICATION_BUFFER_CAPACITY: usize = 256;

/// An identifier generated by this client for one JSON-RPC request.
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq, PartialOrd, Ord)]
pub struct RequestId(u64);

impl RequestId {
    pub(crate) const fn new(value: u64) -> Self {
        Self(value)
    }

    /// Returns the numeric JSON-RPC request identifier.
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl fmt::Display for RequestId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

/// A raw JSON-RPC notification received from the management endpoint.
#[derive(Clone, Debug, PartialEq)]
pub struct Notification {
    /// Fully-qualified notification method, for example
    /// `minecraft:notification/players/joined`.
    pub method: String,
    /// Notification parameters, when the peer included them.
    pub params: Option<Value>,
}

/// The current lifecycle state of a client connection.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ConnectionState {
    /// WebSocket handshake succeeded and requests can be sent.
    Connected,
    /// Shutdown was requested and connection tasks are draining.
    Closing,
    /// The connection has shut down cleanly or the peer closed it.
    Closed,
    /// A transport or protocol failure terminated the connection.
    Failed,
}

/// Builder for a [`Client`].
#[derive(Clone, Debug)]
pub struct ClientBuilder {
    endpoint: Url,
    auth: Option<Auth>,
    origin: Option<String>,
    request_timeout: Duration,
    channel_capacity: usize,
}

impl ClientBuilder {
    /// Creates a builder targeting an MCSMP WebSocket endpoint.
    pub fn new(endpoint: Url) -> Self {
        Self {
            endpoint,
            auth: None,
            origin: None,
            request_timeout: DEFAULT_REQUEST_TIMEOUT,
            channel_capacity: DEFAULT_CHANNEL_CAPACITY,
        }
    }

    /// Sets handshake authentication.
    pub fn auth(mut self, auth: Auth) -> Self {
        self.auth = Some(auth);
        self
    }

    /// Sets the optional HTTP `Origin` header used by servers with an allowed
    /// origins policy.
    pub fn origin(mut self, origin: impl Into<String>) -> Self {
        self.origin = Some(origin.into());
        self
    }

    /// Sets the maximum time a JSON-RPC call waits for its response.
    pub fn request_timeout(mut self, timeout: Duration) -> Self {
        self.request_timeout = timeout;
        self
    }

    /// Sets the number of requests that can wait in the local writer queue.
    ///
    /// The value must be greater than zero.
    pub fn channel_capacity(mut self, capacity: usize) -> Self {
        self.channel_capacity = capacity;
        self
    }

    /// Opens the WebSocket and starts the reader and writer tasks.
    pub async fn connect(self) -> Result<Client> {
        validate_builder(&self)?;
        let request = self.handshake_request()?;
        let (socket, _) = connect_async(request).await.map_err(map_connect_error)?;
        Ok(Client::from_socket(socket, self))
    }

    fn handshake_request(
        &self,
    ) -> Result<tokio_tungstenite::tungstenite::handshake::client::Request> {
        let mut request = self
            .endpoint
            .as_str()
            .into_client_request()
            .map_err(|error| {
                Error::configuration(format!("invalid websocket endpoint: {error}"))
            })?;

        match self
            .auth
            .as_ref()
            .expect("builder was validated before handshake")
        {
            Auth::Bearer(secret) => set_header(
                request.headers_mut(),
                AUTHORIZATION,
                &format!("Bearer {}", secret.expose()),
            )?,
            Auth::WebSocketSubprotocol(secret) => set_header(
                request.headers_mut(),
                SEC_WEBSOCKET_PROTOCOL,
                &format!("minecraft-v1,{}", secret.expose()),
            )?,
            Auth::None => {}
        }

        if let Some(origin) = &self.origin {
            set_header(request.headers_mut(), ORIGIN, origin)?;
        }

        Ok(request)
    }
}

fn validate_builder(builder: &ClientBuilder) -> Result<()> {
    match builder.endpoint.scheme() {
        "ws" | "wss" => {}
        scheme => {
            return Err(Error::configuration(format!(
                "MCSMP endpoint scheme must be ws or wss, got `{scheme}`"
            )));
        }
    }
    if builder.endpoint.host_str().is_none() {
        return Err(Error::configuration("MCSMP endpoint must include a host"));
    }
    if builder.auth.is_none() {
        return Err(Error::AuthenticationNotConfigured);
    }
    if builder.request_timeout.is_zero() {
        return Err(Error::configuration(
            "request timeout must be greater than zero",
        ));
    }
    if builder.channel_capacity == 0 {
        return Err(Error::configuration(
            "channel capacity must be greater than zero",
        ));
    }
    Ok(())
}

fn set_header(
    headers: &mut tokio_tungstenite::tungstenite::http::HeaderMap,
    name: tokio_tungstenite::tungstenite::http::header::HeaderName,
    value: &str,
) -> Result<()> {
    let value = HeaderValue::from_str(value)
        .map_err(|error| Error::configuration(format!("invalid `{name}` header value: {error}")))?;
    headers.insert(name, value);
    Ok(())
}

fn map_connect_error(error: WebSocketError) -> Error {
    match error {
        WebSocketError::Http(response) if response.status().as_u16() == 401 => {
            Error::AuthenticationRejected { status: 401 }
        }
        error => Error::transport(error.to_string()),
    }
}

/// An asynchronous, cloneable MCSMP WebSocket client.
#[derive(Clone, Debug)]
pub struct Client {
    inner: Arc<ClientInner>,
}

impl Client {
    /// Starts building a client for `endpoint`.
    pub fn builder(endpoint: Url) -> ClientBuilder {
        ClientBuilder::new(endpoint)
    }

    fn from_socket<S>(socket: tokio_tungstenite::WebSocketStream<S>, builder: ClientBuilder) -> Self
    where
        S: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin + Send + 'static,
    {
        let (outbound_tx, outbound_rx) = mpsc::channel(builder.channel_capacity);
        let (notifications, _) = broadcast::channel(NOTIFICATION_BUFFER_CAPACITY);
        let (shutdown_tx, shutdown_rx) = watch::channel(false);
        let inner = Arc::new(ClientInner {
            outbound_tx,
            pending: Mutex::new(HashMap::new()),
            next_id: AtomicU64::new(1),
            notifications,
            shutdown_tx,
            state: RwLock::new(ConnectionState::Connected),
            request_timeout: builder.request_timeout,
            tasks: Mutex::new(None),
        });

        let (sink, stream) = socket.split();
        let reader = tokio::spawn(reader_task(Arc::clone(&inner), stream, shutdown_rx.clone()));
        let writer = tokio::spawn(writer_task(
            Arc::clone(&inner),
            sink,
            outbound_rx,
            shutdown_rx,
        ));
        *inner.tasks.lock().expect("task lock poisoned") = Some(ConnectionTasks { reader, writer });

        Self { inner }
    }

    /// Returns the current connection lifecycle state.
    pub fn state(&self) -> ConnectionState {
        *self.inner.state.read().expect("state lock poisoned")
    }

    /// Subscribes to raw JSON-RPC notifications.
    ///
    /// Each receiver has its own cursor. If a receiver falls behind the bounded
    /// buffer, `broadcast::error::RecvError::Lagged` reports the number missed.
    pub fn subscribe_notifications(&self) -> broadcast::Receiver<Notification> {
        self.inner.notifications.subscribe()
    }

    /// Returns an untyped JSON-RPC API for MCSMP and extension namespaces.
    pub fn raw(&self) -> RawApi {
        RawApi::new(self.clone())
    }

    /// Closes the socket, stops background tasks, and fails outstanding calls.
    pub async fn shutdown(&self) -> Result<()> {
        let preserve_failed_state = {
            let mut state = self.inner.state.write().expect("state lock poisoned");
            let failed = *state == ConnectionState::Failed;
            if matches!(
                *state,
                ConnectionState::Connected | ConnectionState::Closing
            ) {
                *state = ConnectionState::Closing;
            }
            failed
        };

        let _ = self.inner.shutdown_tx.send(true);
        self.inner.fail_all(Error::Closed);

        let tasks = self.inner.tasks.lock().expect("task lock poisoned").take();
        if let Some(tasks) = tasks {
            let _ = tasks.reader.await;
            let _ = tasks.writer.await;
        }

        if !preserve_failed_state {
            *self.inner.state.write().expect("state lock poisoned") = ConnectionState::Closed;
        }
        Ok(())
    }

    pub(crate) async fn call_value(&self, method: &str, params: Option<Value>) -> Result<Value> {
        if self.state() != ConnectionState::Connected {
            return Err(Error::Closed);
        }

        let id = self.inner.next_request_id();
        let text = serialize_request(id, method, params)?;
        let (sender, receiver) = oneshot::channel();
        self.inner
            .pending
            .lock()
            .expect("pending lock poisoned")
            .insert(id, sender);

        let outbound = OutboundRequest { id, text };
        if self
            .inner
            .outbound_tx
            .send(Outbound::Request(outbound))
            .await
            .is_err()
        {
            self.inner.remove_pending(id);
            return Err(Error::Closed);
        }

        match timeout(self.inner.request_timeout, receiver).await {
            Ok(Ok(result)) => result,
            Ok(Err(_)) => Err(Error::Closed),
            Err(_) => {
                self.inner.remove_pending(id);
                Err(Error::Timeout {
                    id,
                    method: method.to_owned(),
                })
            }
        }
    }
}

struct ClientInner {
    outbound_tx: mpsc::Sender<Outbound>,
    pending: Mutex<HashMap<RequestId, oneshot::Sender<Result<Value>>>>,
    next_id: AtomicU64,
    notifications: broadcast::Sender<Notification>,
    shutdown_tx: watch::Sender<bool>,
    state: RwLock<ConnectionState>,
    request_timeout: Duration,
    tasks: Mutex<Option<ConnectionTasks>>,
}

impl fmt::Debug for ClientInner {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ClientInner")
            .field("state", &self.state.read().ok())
            .field("request_timeout", &self.request_timeout)
            .finish_non_exhaustive()
    }
}

impl ClientInner {
    fn next_request_id(&self) -> RequestId {
        loop {
            let id = self.next_id.fetch_add(1, Ordering::Relaxed);
            if id != 0 {
                return RequestId::new(id);
            }
        }
    }

    fn resolve_pending(&self, id: RequestId, result: Result<Value>) -> bool {
        let sender = self
            .pending
            .lock()
            .expect("pending lock poisoned")
            .remove(&id);
        sender.is_some_and(|sender| sender.send(result).is_ok())
    }

    fn remove_pending(&self, id: RequestId) {
        let _ = self
            .pending
            .lock()
            .expect("pending lock poisoned")
            .remove(&id);
    }

    fn fail_all(&self, error: Error) {
        let pending = std::mem::take(&mut *self.pending.lock().expect("pending lock poisoned"));
        for (_, sender) in pending {
            let _ = sender.send(Err(error.clone()));
        }
    }

    fn close_terminally(&self) {
        let should_signal = {
            let mut state = self.state.write().expect("state lock poisoned");
            match *state {
                ConnectionState::Connected => {
                    *state = ConnectionState::Closed;
                    true
                }
                ConnectionState::Closing | ConnectionState::Closed | ConnectionState::Failed => {
                    false
                }
            }
        };

        if should_signal {
            self.fail_all(Error::Closed);
            let _ = self.shutdown_tx.send(true);
        }
    }

    fn fail_terminally(&self, error: Error) {
        let should_signal = {
            let mut state = self.state.write().expect("state lock poisoned");
            match *state {
                ConnectionState::Closing | ConnectionState::Closed | ConnectionState::Failed => {
                    false
                }
                ConnectionState::Connected => {
                    *state = ConnectionState::Failed;
                    true
                }
            }
        };

        if should_signal {
            self.fail_all(error);
            let _ = self.shutdown_tx.send(true);
        }
    }
}

struct ConnectionTasks {
    reader: JoinHandle<()>,
    writer: JoinHandle<()>,
}

/// Messages owned by the single WebSocket writer task.
#[derive(Debug)]
enum Outbound {
    Request(OutboundRequest),
    Control(Message),
}

async fn reader_task<S>(inner: Arc<ClientInner>, mut stream: S, mut shutdown: watch::Receiver<bool>)
where
    S: futures_util::Stream<Item = std::result::Result<Message, WebSocketError>> + Unpin,
{
    loop {
        tokio::select! {
            changed = shutdown.changed() => {
                if changed.is_err() || *shutdown.borrow() {
                    break;
                }
            }
            message = stream.next() => {
                let Some(message) = message else {
                    inner.close_terminally();
                    break;
                };

                match message {
                    Ok(Message::Text(text)) => {
                        match parse_inbound(text.as_ref()) {
                            Ok(Inbound::Response { id, result }) => {
                                let _ = inner.resolve_pending(id, result);
                            }
                            Ok(Inbound::Notification { method, params }) => {
                                let _ = inner.notifications.send(Notification { method, params });
                            }
                            Err(error) => {
                                inner.fail_terminally(error);
                                break;
                            }
                        }
                    }
                    Ok(Message::Ping(payload)) => {
                        // The writer is the sole owner of the sink. Queue the matching pong
                        // rather than writing from the reader task.
                        if inner.outbound_tx.try_send(Outbound::Control(Message::Pong(payload))).is_err() {
                            inner.fail_terminally(Error::transport("unable to queue WebSocket pong"));
                            break;
                        }
                    }
                    Ok(Message::Pong(_)) => {}
                    Ok(Message::Close(_)) => {
                        inner.close_terminally();
                        break;
                    }
                    Ok(Message::Binary(_)) => {
                        inner.fail_terminally(Error::protocol("binary WebSocket frames are not valid MCSMP JSON-RPC text"));
                        break;
                    }
                    Ok(_) => {
                        inner.fail_terminally(Error::protocol("unsupported WebSocket frame received from peer"));
                        break;
                    }
                    Err(error) => {
                        inner.fail_terminally(Error::transport(error.to_string()));
                        break;
                    }
                }
            }
        }
    }
}

async fn writer_task<S>(
    inner: Arc<ClientInner>,
    mut sink: S,
    mut outbound: mpsc::Receiver<Outbound>,
    mut shutdown: watch::Receiver<bool>,
) where
    S: futures_util::Sink<Message, Error = WebSocketError> + Unpin,
{
    loop {
        tokio::select! {
            changed = shutdown.changed() => {
                if changed.is_err() || *shutdown.borrow() {
                    let _ = sink.send(Message::Close(None)).await;
                    break;
                }
            }
            request = outbound.recv() => {
                let Some(outbound) = request else {
                    let _ = sink.send(Message::Close(None)).await;
                    break;
                };

                let message = match outbound {
                    Outbound::Request(request) => Message::Text(request.text.into()),
                    Outbound::Control(message) => message,
                };
                if let Err(error) = sink.send(message).await {
                    inner.fail_terminally(Error::transport(error.to_string()));
                    break;
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use futures_util::{SinkExt, StreamExt};
    use serde_json::{json, Value};
    use tokio::net::TcpListener;
    use tokio_tungstenite::accept_async;
    use tokio_tungstenite::tungstenite::Message;
    use url::Url;

    use super::*;

    #[test]
    fn bearer_handshake_contains_authorization_and_origin() {
        let builder = Client::builder(Url::parse("wss://localhost:25585").unwrap())
            .auth(Auth::bearer("secret").unwrap())
            .origin("mcsmp-rs-test");
        let request = builder.handshake_request().unwrap();
        assert_eq!(request.headers()[AUTHORIZATION], "Bearer secret");
        assert_eq!(request.headers()[ORIGIN], "mcsmp-rs-test");
    }

    #[test]
    fn subprotocol_handshake_contains_browser_compatible_credentials() {
        let builder = Client::builder(Url::parse("ws://localhost:25585").unwrap())
            .auth(Auth::websocket_subprotocol("secret").unwrap());
        let request = builder.handshake_request().unwrap();
        assert_eq!(
            request.headers()[SEC_WEBSOCKET_PROTOCOL],
            "minecraft-v1,secret"
        );
    }

    #[test]
    fn endpoint_requires_explicit_authentication_choice() {
        let error = Client::builder(Url::parse("ws://localhost:25585").unwrap()).connect();
        let runtime = tokio::runtime::Runtime::new().unwrap();
        let error = runtime.block_on(error).unwrap_err();
        assert_eq!(error, Error::AuthenticationNotConfigured);
    }

    #[tokio::test]
    async fn multiplexes_out_of_order_responses() {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();

        tokio::spawn(async move {
            let (stream, _) = listener.accept().await.unwrap();
            let mut socket = accept_async(stream).await.unwrap();
            let mut requests = Vec::new();
            while requests.len() < 2 {
                let message = socket.next().await.unwrap().unwrap();
                if let Message::Text(text) = message {
                    requests.push(serde_json::from_str::<Value>(text.as_ref()).unwrap());
                }
            }
            for request in requests.into_iter().rev() {
                let response = json!({
                    "jsonrpc": "2.0",
                    "id": request["id"],
                    "result": request["method"],
                });
                socket
                    .send(Message::Text(response.to_string().into()))
                    .await
                    .unwrap();
            }
        });

        let client = Client::builder(Url::parse(&format!("ws://{address}")).unwrap())
            .auth(Auth::none())
            .connect()
            .await
            .unwrap();

        let raw_client = client.raw();
        let first = raw_client.call_value("one", None);
        let second = raw_client.call_value("two", None);
        let (first, second) = tokio::join!(first, second);
        assert_eq!(first.unwrap(), json!("one"));
        assert_eq!(second.unwrap(), json!("two"));
        client.shutdown().await.unwrap();
    }

    #[tokio::test]
    async fn broadcasts_notification_before_response() {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();

        tokio::spawn(async move {
            let (stream, _) = listener.accept().await.unwrap();
            let mut socket = accept_async(stream).await.unwrap();
            let request = socket.next().await.unwrap().unwrap();
            let Message::Text(text) = request else {
                panic!("expected JSON-RPC text")
            };
            let request: Value = serde_json::from_str(text.as_ref()).unwrap();
            socket
                .send(Message::Text(
                    json!({
                        "jsonrpc": "2.0",
                        "method": "minecraft:notification/players/joined",
                        "params": {"player": "Alex"}
                    })
                    .to_string()
                    .into(),
                ))
                .await
                .unwrap();
            socket
                .send(Message::Text(
                    json!({
                        "jsonrpc": "2.0",
                        "id": request["id"],
                        "result": true
                    })
                    .to_string()
                    .into(),
                ))
                .await
                .unwrap();
        });

        let client = Client::builder(Url::parse(&format!("ws://{address}")).unwrap())
            .auth(Auth::none())
            .connect()
            .await
            .unwrap();
        let mut notifications = client.subscribe_notifications();
        assert_eq!(
            client.raw().call_value("x", None).await.unwrap(),
            json!(true)
        );
        let notification = notifications.recv().await.unwrap();
        assert_eq!(notification.method, "minecraft:notification/players/joined");
        assert_eq!(notification.params, Some(json!({"player": "Alex"})));
        client.shutdown().await.unwrap();
    }

    #[tokio::test]
    async fn propagates_remote_json_rpc_errors() {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();

        tokio::spawn(async move {
            let (stream, _) = listener.accept().await.unwrap();
            let mut socket = accept_async(stream).await.unwrap();
            let message = socket.next().await.unwrap().unwrap();
            let Message::Text(text) = message else {
                panic!("expected JSON-RPC text")
            };
            let request: Value = serde_json::from_str(text.as_ref()).unwrap();
            socket
                .send(Message::Text(
                    json!({
                        "jsonrpc": "2.0",
                        "id": request["id"],
                        "error": {"code": -32601, "message": "method not found"}
                    })
                    .to_string()
                    .into(),
                ))
                .await
                .unwrap();
        });

        let client = Client::builder(Url::parse(&format!("ws://{address}")).unwrap())
            .auth(Auth::none())
            .connect()
            .await
            .unwrap();
        let error = client.raw().call_value("missing", None).await.unwrap_err();
        assert!(matches!(
            error,
            Error::Remote(crate::RemoteError { code: -32601, .. })
        ));
        client.shutdown().await.unwrap();
    }

    #[tokio::test]
    async fn removes_timed_out_requests_from_pending_map() {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        tokio::spawn(async move {
            let (stream, _) = listener.accept().await.unwrap();
            let mut socket = accept_async(stream).await.unwrap();
            let _ = socket.next().await;
            tokio::time::sleep(Duration::from_millis(100)).await;
        });

        let client = Client::builder(Url::parse(&format!("ws://{address}")).unwrap())
            .auth(Auth::none())
            .request_timeout(Duration::from_millis(10))
            .connect()
            .await
            .unwrap();

        let error = client.raw().call_value("slow", None).await.unwrap_err();
        assert!(matches!(error, Error::Timeout { .. }));
        assert!(client.inner.pending.lock().unwrap().is_empty());
        client.shutdown().await.unwrap();
    }
}
