//! Public client facade and connection builder.
//!
//! WebSocket handshake construction lives in `connection`; the mutable
//! multiplexing, notification, and reconnection runtime lives in `runtime`.
//! This module deliberately contains only the public MCSMP-facing API.

use std::fmt;
use std::sync::Arc;
use std::time::Duration;

use serde_json::Value;
use tokio::sync::broadcast;
use url::Url;

use crate::api::{
    AllowlistApi, BansApi, GamerulesApi, IpBansApi, OperatorsApi, PlayersApi, ServerApi,
    ServerSettingsApi,
};
use crate::connection::{open_socket, ReconnectConfig, Socket};
use crate::event::{EventStream, RawNotification};
use crate::runtime::{start_session, ClientInner, RuntimeConfig};
use crate::{Auth, Capabilities, CompatibilityMode, Error, RawApi, ReconnectPolicy, Result};

const DEFAULT_REQUEST_TIMEOUT: Duration = Duration::from_secs(10);
const DEFAULT_CHANNEL_CAPACITY: usize = 128;

/// An identifier generated by this client for one JSON-RPC request.
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq, PartialOrd, Ord)]
pub struct RequestId(u64);

impl RequestId {
    pub(crate) const fn new(value: u64) -> Self {
        Self(value)
    }

    /// Returns the numeric JSON-RPC request identifier.
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl fmt::Display for RequestId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

/// Backwards-compatible public name for an untyped notification.
pub use crate::event::RawNotification as Notification;


/// The current lifecycle state of a client connection.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum ConnectionState {
    /// WebSocket handshake succeeded and requests can be sent.
    Connected,
    /// The client is waiting before or attempting an automatic reconnection.
    ///
    /// Calls made in this state return [`Error::Reconnecting`]. The client does
    /// not retain or replay calls from the preceding connection.
    Reconnecting,
    /// Shutdown was requested and connection tasks are draining.
    Closing,
    /// The connection has shut down cleanly or the peer closed it.
    Closed,
    /// A transport/protocol failure terminated the connection permanently.
    Failed,
}

/// Builder for a [`Client`].
#[derive(Clone, Debug)]
pub struct ClientBuilder {
    endpoint: Url,
    auth: Option<Auth>,
    origin: Option<String>,
    request_timeout: Duration,
    channel_capacity: usize,
    compatibility_mode: CompatibilityMode,
    reconnect_policy: ReconnectPolicy,
}

impl ClientBuilder {
    /// Creates a builder targeting an MCSMP WebSocket endpoint.
    pub fn new(endpoint: Url) -> Self {
        Self {
            endpoint,
            auth: None,
            origin: None,
            request_timeout: DEFAULT_REQUEST_TIMEOUT,
            channel_capacity: DEFAULT_CHANNEL_CAPACITY,
            compatibility_mode: CompatibilityMode::default(),
            reconnect_policy: ReconnectPolicy::default(),
        }
    }

    /// Sets handshake authentication.
    pub fn auth(mut self, auth: Auth) -> Self {
        self.auth = Some(auth);
        self
    }

    /// Sets the optional HTTP `Origin` header used by servers with an allowed
    /// origins policy.
    pub fn origin(mut self, origin: impl Into<String>) -> Self {
        self.origin = Some(origin.into());
        self
    }

    /// Sets the maximum time a JSON-RPC call waits for its response.
    pub fn request_timeout(mut self, timeout: Duration) -> Self {
        self.request_timeout = timeout;
        self
    }

    /// Sets the number of requests that can wait in the local writer queue.
    ///
    /// The value must be greater than zero.
    pub fn channel_capacity(mut self, capacity: usize) -> Self {
        self.channel_capacity = capacity;
        self
    }

    /// Sets the compatibility policy used when invoking discovered methods and
    /// interpreting historical notification prefixes.
    pub fn compatibility_mode(mut self, mode: CompatibilityMode) -> Self {
        self.compatibility_mode = mode;
        self
    }

    /// Sets the policy used after an unexpected close or transport failure.
    ///
    /// Reconnection never replays in-flight JSON-RPC calls.
    pub fn reconnect_policy(mut self, policy: ReconnectPolicy) -> Self {
        self.reconnect_policy = policy;
        self
    }

    /// Opens the WebSocket and starts the reader/writer tasks.
    pub async fn connect(self) -> Result<Client> {
        validate_builder(&self)?;
        let reconnect_config = self.reconnect_config();
        let socket = open_socket(&reconnect_config).await?;
        Ok(Client::from_socket(socket, self, reconnect_config))
    }

    fn reconnect_config(&self) -> ReconnectConfig {
        ReconnectConfig::new(
            self.endpoint.clone(),
            self.auth
                .clone()
                .expect("builder was validated before a connection was attempted"),
            self.origin.clone(),
        )
    }

    fn handshake_request(
        &self,
    ) -> Result<tokio_tungstenite::tungstenite::handshake::client::Request> {
        self.reconnect_config().handshake_request()
    }
}

fn validate_builder(builder: &ClientBuilder) -> Result<()> {
    match builder.endpoint.scheme() {
        "ws" | "wss" => {}
        scheme => {
            return Err(Error::configuration(format!(
                "MCSMP endpoint scheme must be ws or wss, got `{scheme}`"
            )));
        }
    }
    if builder.endpoint.host_str().is_none() {
        return Err(Error::configuration("MCSMP endpoint must include a host"));
    }
    if builder.auth.is_none() {
        return Err(Error::AuthenticationNotConfigured);
    }
    if builder.request_timeout.is_zero() {
        return Err(Error::configuration(
            "request timeout must be greater than zero",
        ));
    }
    if builder.channel_capacity == 0 {
        return Err(Error::configuration(
            "channel capacity must be greater than zero",
        ));
    }
    builder
        .reconnect_policy
        .validate()
        .map_err(Error::configuration)?;
    Ok(())
}

/// An asynchronous, cloneable MCSMP WebSocket client.
#[derive(Clone, Debug)]
pub struct Client {
    inner: Arc<ClientInner>,
}

impl Client {
    /// Starts building a client for `endpoint`.
    pub fn builder(endpoint: Url) -> ClientBuilder {
        ClientBuilder::new(endpoint)
    }

    fn from_socket(
        socket: Socket,
        builder: ClientBuilder,
        reconnect_config: ReconnectConfig,
    ) -> Self {
        let runtime_config = RuntimeConfig {
            request_timeout: builder.request_timeout,
            channel_capacity: builder.channel_capacity,
            compatibility_mode: builder.compatibility_mode,
            reconnect_policy: builder.reconnect_policy,
            reconnect_config,
        };
        let inner = Arc::new(ClientInner::new(runtime_config));
        start_session(&inner, socket);
        Self { inner }
    }

    pub(crate) fn from_inner(inner: Arc<ClientInner>) -> Self {
        Self { inner }
    }

    /// Returns the current connection lifecycle state.
    pub fn state(&self) -> ConnectionState {
        self.inner.state()
    }

    /// Subscribes to strongly typed MCSMP notifications.
    ///
    /// The returned stream reports lag through [`crate::EventStreamError`].
    /// Query the relevant API after lag to rebuild an authoritative local view.
    pub fn subscribe(&self) -> EventStream {
        EventStream::new(
            self.inner.subscribe_events(),
            self.inner.subscribe_event_shutdown(),
        )
    }

    /// Subscribes to normalized raw JSON-RPC notifications.
    ///
    /// Each receiver has its own cursor. If a receiver falls behind the bounded
    /// buffer, `broadcast::error::RecvError::Lagged` reports the number missed.
    pub fn subscribe_notifications(&self) -> broadcast::Receiver<RawNotification> {
        self.inner.subscribe_raw_notifications()
    }

    /// Returns an untyped JSON-RPC API for MCSMP and extension namespaces.
    pub fn raw(&self) -> RawApi {
        RawApi::new(self.clone())
    }

    /// Returns strongly typed allowlist operations.
    pub fn allowlist(&self) -> AllowlistApi {
        AllowlistApi::new(self.clone())
    }

    /// Returns strongly typed user-ban operations.
    pub fn bans(&self) -> BansApi {
        BansApi::new(self.clone())
    }

    /// Returns strongly typed IP-ban operations.
    pub fn ip_bans(&self) -> IpBansApi {
        IpBansApi::new(self.clone())
    }

    /// Returns strongly typed connected-player operations.
    pub fn players(&self) -> PlayersApi {
        PlayersApi::new(self.clone())
    }

    /// Returns strongly typed operator-list operations.
    pub fn operators(&self) -> OperatorsApi {
        OperatorsApi::new(self.clone())
    }

    /// Returns strongly typed server lifecycle and messaging operations.
    pub fn server(&self) -> ServerApi {
        ServerApi::new(self.clone())
    }

    /// Returns strongly typed live server-settings operations.
    pub fn server_settings(&self) -> ServerSettingsApi {
        ServerSettingsApi::new(self.clone())
    }

    /// Returns strongly typed gamerule operations.
    pub fn gamerules(&self) -> GamerulesApi {
        GamerulesApi::new(self.clone())
    }

    /// Returns the configured capability-compatibility policy.
    pub fn compatibility_mode(&self) -> CompatibilityMode {
        self.inner.compatibility_mode()
    }

    /// Returns the configured reconnect policy.
    pub fn reconnect_policy(&self) -> &ReconnectPolicy {
        self.inner.reconnect_policy()
    }

    /// Returns the latest capability snapshot obtained with [`Client::discover`].
    pub fn capabilities(&self) -> Option<Capabilities> {
        self.inner.capabilities()
    }

    /// Calls `rpc.discover`, converts the returned schema into a capability
    /// snapshot, and replaces the client's cached snapshot.
    ///
    /// Discovery itself bypasses strict-mode method gating because it establishes
    /// the schema used for later strict calls. Automatic reconnection clears the
    /// cache and invokes this method once the replacement socket is available.
    pub async fn discover(&self) -> Result<Capabilities> {
        let raw_schema = self.inner.call_value("rpc.discover", None).await?;
        let capabilities = Capabilities::from_schema(raw_schema);
        self.inner.replace_capabilities(capabilities.clone());
        Ok(capabilities)
    }

    /// Closes the socket, stops background tasks, and fails outstanding calls.
    pub async fn shutdown(&self) -> Result<()> {
        self.inner.shutdown().await
    }

    pub(crate) async fn call_typed_value(
        &self,
        method: &str,
        params: Option<Value>,
    ) -> Result<Value> {
        self.inner.ensure_method_allowed(method)?;
        self.inner.call_value(method, params).await
    }

    pub(crate) async fn call_raw_value(
        &self,
        method: &str,
        params: Option<Value>,
    ) -> Result<Value> {
        if method != "rpc.discover" {
            self.inner.ensure_method_allowed(method)?;
        }
        self.inner.call_value(method, params).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tokio_tungstenite::tungstenite::http::header::{
        AUTHORIZATION, ORIGIN, SEC_WEBSOCKET_PROTOCOL,
    };

    #[test]
    fn bearer_handshake_contains_authorization_and_origin() {
        let builder = Client::builder(Url::parse("wss://localhost:25585").unwrap())
            .auth(Auth::bearer("secret").unwrap())
            .origin("mcsmp-rs-test");
        let request = builder.handshake_request().unwrap();
        assert_eq!(request.headers()[AUTHORIZATION], "Bearer secret");
        assert_eq!(request.headers()[ORIGIN], "mcsmp-rs-test");
    }

    #[test]
    fn subprotocol_handshake_contains_browser_compatible_credentials() {
        let builder = Client::builder(Url::parse("ws://localhost:25585").unwrap())
            .auth(Auth::websocket_subprotocol("secret").unwrap());
        let request = builder.handshake_request().unwrap();
        assert_eq!(
            request.headers()[SEC_WEBSOCKET_PROTOCOL],
            "minecraft-v1,secret"
        );
    }

    #[test]
    fn builder_rejects_invalid_reconnect_policy() {
        let builder = Client::builder(Url::parse("ws://localhost:25585").unwrap())
            .auth(Auth::none())
            .reconnect_policy(ReconnectPolicy::fixed(Duration::ZERO, Some(1)));
        assert!(matches!(
            validate_builder(&builder),
            Err(Error::Configuration(_))
        ));
    }
}
